import { ArrowUpRight } from "lucide-react";
import { motion, useReducedMotion } from "framer-motion";
import type { Project } from "../../data/projects";
import { ArtifactSVG } from "./ArtifactSVG";
import { ease } from "../../lib/motion";
import { useFeatureDetect } from "../../hooks/useFeatureDetect";

export function ProjectPanel({ project, reverse }: { project: Project; reverse: boolean }) {
  const reduced = useReducedMotion();
  const { isTouch, hasNoHover, isTelegramWebView, isCompact } = useFeatureDetect();
  const staticMotion = Boolean(reduced || isTouch || hasNoHover || isTelegramWebView || isCompact);
  const content = <><div className="relative z-10"><div className="flex items-center justify-between font-mono text-[10px] uppercase tracking-[0.16em] text-zinc-500"><span>{project.index} / {project.eyebrow}</span><span className="text-amber-200">{project.status}</span></div><h3 className="mt-8 whitespace-pre-line text-5xl font-medium leading-[0.82] tracking-[-0.075em] text-[#f2f3f5] sm:text-6xl lg:text-8xl">{project.title}</h3><p className="mt-7 max-w-xl text-base leading-relaxed text-zinc-400">{project.description}</p></div><div className="relative z-10 grid gap-6 border-t border-white/[0.09] pt-6 text-sm md:grid-cols-2"><div><p className="font-mono text-[9px] uppercase tracking-[0.16em] text-zinc-600">Role</p><p className="mt-2 leading-relaxed text-zinc-300">{project.role}</p><p className="mt-5 font-mono text-[9px] uppercase tracking-[0.16em] text-zinc-600">Contribution</p><p className="mt-2 leading-relaxed text-zinc-400">{project.contribution}</p></div><div><p className="font-mono text-[9px] uppercase tracking-[0.16em] text-zinc-600">Outcome</p><p className="mt-2 leading-relaxed text-zinc-300">{project.outcome}</p><p className="mt-5 border-l border-amber-300/50 pl-3 font-mono text-[10px] leading-relaxed text-amber-100/75">{project.proof}</p></div></div><div className="relative z-10 flex flex-wrap items-center justify-between gap-5 border-t border-white/[0.09] pt-5"><div className="flex flex-wrap gap-x-3 gap-y-2 font-mono text-[9px] uppercase tracking-[0.12em] text-zinc-500">{project.stack.map((item) => <span key={item}>/{item}</span>)}</div>{project.link ? <a href={project.link} target="_blank" rel="noreferrer" data-cursor="hover" className="inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.14em] text-cyan-100 transition-colors hover:text-white">Inspect <ArrowUpRight className="h-3.5 w-3.5" /></a> : <span className="font-mono text-[9px] uppercase tracking-[0.14em] text-zinc-600">Awaiting signal</span>}</div></>;
  return <motion.article initial={staticMotion ? false : { opacity: 0, y: 36 }} whileInView={staticMotion ? undefined : { opacity: 1, y: 0 }} viewport={{ once: true, margin: "-90px" }} transition={{ duration: 0.8, ease: ease.cinematic }} className="project-panel group relative grid overflow-hidden border-x border-white/[0.06] px-5 py-7 sm:px-8 sm:py-10 lg:grid-cols-2 lg:gap-16 lg:px-12 lg:py-14"><div className="pointer-events-none absolute inset-0 opacity-0 transition-opacity duration-700 group-hover:opacity-100 project-panel-grid" /><div className="absolute left-0 top-0 h-px w-0 bg-cyan-200 transition-all duration-700 group-hover:w-full" /><div className={`relative flex min-h-[12rem] items-center justify-center overflow-hidden border-b border-white/[0.08] py-4 text-cyan-100/45 lg:min-h-full lg:border-b-0 ${reverse ? "lg:order-2 lg:border-l lg:pl-10" : "lg:border-r lg:pr-10"}`}><ArtifactSVG type={project.artifact} className="w-full max-w-sm transition-all duration-700 group-hover:scale-105 group-hover:text-cyan-100/85" /></div><div className={`flex flex-col justify-between gap-10 pt-7 lg:pt-0 ${reverse ? "lg:order-1" : ""}`}>{content}</div></motion.article>;
}
